language: ruby
bundler_args: --without "oracle sqlserver"

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - bundle exec rake postgresql:build_database mysql:build_database sqlite:build_database

script:
  - "bundle exec rake postgresql:test"
  - "bundle exec rake mysql:test"
  - "bundle exec rake sqlite:test"

rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2

env:
  global:
    - CPK_LOGFILE=log/test.log

services:
  - postgresql
  - mysql
